version: '2'

services:
    php:
        build: ./php
        volumes_from:
            - source
        ports:
            - '9000:9000'
        restart: always
    nginx:
        build: ./nginx
        volumes_from:
            - source
        ports:
            - '8080:8080'
            - '443:443'
        links:
            - php
        restart: always
    source:
        image: alpine:latest
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./logs/php:/var/log/php
            - ./grav:/var/www
            - /etc/localtime:/etc/localtime/:ro
